apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-creds
  namespace: demo
spec:
  refreshInterval: 1m # Đồng bộ lại sau mỗi 1 phút
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: db-secret  # Tên K8s Secret sẽ tự động được sinh ra trong cụm
  data:
  - secretKey: password
    remoteRef:
      key: prod/db/password