apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: alice-developer
rules:
  # Cho phép quản lý Argo Rollouts (vì dự án đang dùng kind: Rollout thay vì Deployment)
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts", "analysistemplates"]
    verbs: ["*"]
  # Cho phép quản lý Deployments tiêu chuẩn (nếu có dùng)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  # Cho phép quản lý Pods, Services, Logs và Exec terminal
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services"]
    verbs: ["*"]