apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: demo
  name: alice-developer
rules:

  - apiGroups: ["argoproj.io"]
    resources: ["rollouts", "analysistemplates"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/exec", "services"]
    verbs: ["*"]