apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: image-policy
spec:
  images:
    - glob: "*"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEfKjj98BeRlMJz6MZI6ARFkHd6urn
          vH5JwAVenOTShomIVwjvFWeRWFk152D5HblGVVoKTfpF/TwzfAQ1pDF1vQ==
          -----END PUBLIC KEY-----
